[workspace]
resolver = "2"
members = [
  "crates/core",
  "crates/cli",
]

[workspace.package]
version = "1.0.0-rc2"
edition = "2021"
authors = ["The Extism Authors"]
license = "BSD-Clause-3"

[workspace.dependencies]
anyhow = "^1.0.68"
